# Generated by Django 4.2.11 on 2024-05-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_color', models.CharField(max_length=7)),
                ('main_color', models.CharField(max_length=7)),
                ('length', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('style', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
